[project]
name = "informer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nuitka>=4.0",
    "psutil>=7.2.2",
    "requests>=2.32.5",
    "zstandard>=0.25.0",
]
